### ISSUE TITLE
Request for number_format_insert to support number that already have thousands separators (commas) and decimal point

### ISSUE THREAD

**Issue by winstond** [Volensia/plover_number_format#1]
Example:
1. This works...
1555715
then apply using a stroke the translation {:number_format_insert:$nnn,nnn,nnn,nnN}, I get:
$1,555,715

2. This doesn't work...
1,555,715 (phoenix stroke for this would be  WUPB/PH*L/TPAOEUFB/H-PB/STKPWOEUFB/TH*/SAEFB/H-PB/STKPWAEPB)
then apply using a stroke the translation {:number_format_insert:$nnn,nnn,nnn,nnN}, I get:
$1,5,55,,715

Not urgent, but certainly would make this perfect for someone who already learned to stroke numbers "as they hear the speaker say them" as taught in the Phoenix courses.

**Comment by Volensia** [comment]
fixed by IQubic
