### ISSUE TITLE
Number Word Conversion fails on numbers over 16

### ISSUE THREAD

**Issue by winstond** [Volensia/plover_number_format#2]
Steps to reproduce:

1. Map a stroke to {:number_word_conversion:1:2}
2. Stroke "15" followed by the above stroke --> result is "fifteen" as expected
3. Stroke "17" followed by the above stroke --> result is "eighteen" (incorrect)
4. Stroke "19" followed by the above stroke --> result is an error popup

**Comment by Volensia** [comment]
fixed in version 1.1.0
that was such a silly mistake lol, I forgot to define "seventeen" so 19 was out range of the array
