### ISSUE TITLE
Treatment of number converted to "word"

### ISSUE THREAD

**Issue by winstond** [Volensia/plover_number_format#3]
If a number is converted to a word, then it should behave as a word (i.e. the next thing stroked should have a space before it).
This happens if you happen to stroke a word, but if you stroke a number it doesn't and instead "attaches".

Example:
Stroke the number "15"
Use a defined stroke to convert it to the word "fifteen"
Now stroke another number as usual, for example "10"
The result will be:
 --> fifteen10
The preferred result should be:
--> fifteen 10

Here's a real life example:
"He gave me fifteen 10-dollar bills."

**Comment by Volensia** [comment]
fixed by IQubic
