### ISSUE TITLE
Convert to word beginning of a sentence ideally should be capitalized

### ISSUE THREAD

**Issue by winstond** [Volensia/plover_number_format#4]
If you stroke some sentence, follow it by a number, then "convert" the number to a word using a stroke, the word should be capitalized.

Example:
I don't know what he did.  2 times I asked him what was he thinking?
(If I pressed a "convert to word" stroke after 2, I would hope to get "Two", but currently get "two")

**Comment by Volensia** [comment]
fixed by IQubic
